# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0003_auto_20160912_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='EncounterStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Display Name')),
                ('code', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='encounter',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encounter.EncounterStatus'),
        ),
    ]
