# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounter', '0002_auto_20160912_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
