# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encounter', '0003_auto_20160912_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterDiagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True, max_length=500, verbose_name='Diagnosis')),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='Special Notes')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Encounter Diagnoses',
            },
        ),
        migrations.CreateModel(
            name='EncounterPatientExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination', models.TextField(blank=True, max_length=500, verbose_name='Examination')),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='Special Notes')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Encounter Examinations',
            },
        ),
        migrations.CreateModel(
            name='EncounterPatientHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(blank=True, max_length=500, verbose_name='History')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Encounter History',
            },
        ),
        migrations.AddField(
            model_name='encounter',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='notes',
            field=models.TextField(blank=True, max_length=500, verbose_name='Special Notes'),
        ),
        migrations.AddField(
            model_name='encounterpatienthistory',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encounter.Encounter'),
        ),
        migrations.AddField(
            model_name='encounterpatientexamination',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encounter.Encounter'),
        ),
        migrations.AddField(
            model_name='encounterdiagnosis',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encounter.Encounter'),
        ),
    ]
