# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 14:10
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone

def gen_dates(apps, schema_editor):
    Encounter = apps.get_model('encounter', 'Encounter')
    for row in Encounter.objects.all():
        row.date_created = timezone.now()
        row.last_modified = timezone.now()
        row.save()

class Migration(migrations.Migration):

    
    dependencies = [
        ('encounter', '0004_add_encounter_models'),
    ]

    operations = [
        migrations.RunPython(gen_dates,
                             reverse_code=migrations.RunPython.noop),
    ]
