# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounter', '0005_populate_added_date_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
