# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20160912_0436'),
        ('encounter', '0006_make_date_fields_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientEncounterVitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='encounter',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='patientencountervitals',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encounter.Encounter'),
        ),
        migrations.AddField(
            model_name='patientencountervitals',
            name='patientvitals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.PatientVitals'),
        ),
    ]
