# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 09:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encounter', '0002_remove_patient_add_encounter_to_patientvitals'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticServiceSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=100, verbose_name='Units')),
                ('reference_value', models.CharField(blank=True, max_length=200, null=True)),
                ('maximum', models.CharField(blank=True, max_length=100, verbose_name='Maximum Value')),
                ('minimum', models.CharField(blank=True, max_length=100, verbose_name='Minimum Value')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.DiagnosticServiceSection')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PatientLabReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(blank=True, null=True)),
                ('report_time', models.DateTimeField(auto_now=True)),
                ('report_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='PatientLabRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(blank=True, max_length=1000, null=True)),
                ('request_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('request_time', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encounter.Encounter')),
                ('requestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.ObservationGroup'),
        ),
    ]
