# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticServiceSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('maximum', models.CharField(blank=True, max_length=100, verbose_name='Maximum Value')),
                ('minimum', models.CharField(blank=True, max_length=100, verbose_name='Minimum Value')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.DiagnosticServiceSection')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.ObservationGroup'),
        ),
    ]
