# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 11:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0002_auto_20161019_1154'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientlabrequest',
            name='request_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='radiology.RequestStatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientlabreport',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
