# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('encounter', '0008_auto_20161012_0718'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PatientLabInvestigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('request_time', models.DateTimeField(auto_now=True)),
                ('report_time', models.DateTimeField(auto_now=True)),
                ('report_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encounter.Encounter')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Staff')),
                ('requestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_officer', to='staff.Staff')),
            ],
        ),
    ]
