# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-20 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_replace_Staff_with_User_add_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
