# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='iso_3code',
            new_name='alpha_three',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='iso_2code',
            new_name='alpha_two',
        ),
    ]
