# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_auto_20160907_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
