# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 08:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonRelative',
            fields=[
                ('personcontact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.PersonContact')),
                ('full_name', models.CharField(max_length=200, verbose_name='Relative Name')),
            ],
            bases=('person.personcontact',),
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Relationship Name')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='personcontact',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 12, 8, 45, 58, 211434, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personcontact',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 12, 8, 46, 9, 383036, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persondemographic',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 12, 8, 46, 17, 211726, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persondemographic',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 12, 8, 46, 28, 903373, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personphoto',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 12, 8, 46, 36, 939763, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personphoto',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 12, 8, 46, 47, 264400, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personrelative',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Relationship'),
        ),
    ]
