# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name_plural': 'Gender'},
        ),
        migrations.AlterModelOptions(
            name='maritalstatus',
            options={'verbose_name': 'Marital Status', 'verbose_name_plural': 'Marital Status'},
        ),
        migrations.AlterModelOptions(
            name='persondemographic',
            options={'verbose_name': 'Person Demographic'},
        ),
        migrations.AlterModelOptions(
            name='personphoto',
            options={'verbose_name': 'Person Photo'},
        ),
        migrations.AlterModelOptions(
            name='prefix',
            options={'verbose_name_plural': 'Prefixes'},
        ),
    ]
