# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20160907_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='personcontact',
            name='mailing_address',
            field=models.TextField(blank=True, max_length=200, verbose_name='Mailing Address'),
        ),
    ]
