# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20160913_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='id_number',
            field=models.CharField(default='00-00-00', editable=False, max_length=200, null=True, verbose_name='ID Number'),
        ),
    ]
