# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 08:03
from __future__ import unicode_literals

from django.db import migrations


def gen_id_number(apps, schema_editor):
    Person = apps.get_model('person', 'Person')
    for row in Person.objects.all():
        row.id_number = "00-00-{}".format(row.id if len(str(row.id)) > 1 else "0"+str(row.id))
        row.save()
class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_add_field_person_id_number'),
    ]

    operations = [
        migrations.RunPython(gen_id_number,
                             reverse_code=migrations.RunPython.noop),
    ]
