# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_populate_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_number',
            field=models.CharField(default='00-00-00', editable=False, max_length=200, unique=True, verbose_name='ID Number'),
        ),
    ]
