# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0002_auto_20160907_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.Person')),
            ],
            bases=('person.person',),
        ),
    ]
