# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.Person')),
            ],
            bases=('person.person',),
        ),
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('personcontact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.PersonContact')),
            ],
            bases=('person.personcontact',),
        ),
        migrations.CreateModel(
            name='PatientDemographic',
            fields=[
                ('persondemographic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.PersonDemographic')),
            ],
            bases=('person.persondemographic',),
        ),
    ]
