# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_add_date_fields_person_relative'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRelative',
            fields=[
                ('personrelative_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.PersonRelative')),
            ],
            bases=('person.personrelative',),
        ),
    ]
