# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_personcontact_mailing_address'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('personcontact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.PersonContact')),
            ],
            bases=('person.personcontact',),
        ),
        migrations.CreateModel(
            name='PatientDemographic',
            fields=[
                ('persondemographic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.PersonDemographic')),
            ],
            bases=('person.persondemographic',),
        ),
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measures', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
