# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 08:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encounter', '0002_remove_patient_add_encounter_to_patientvitals'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRadioReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('report_time', models.TimeField(default=django.utils.timezone.now)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Image')),
                ('thumbnail_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Image')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiologist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRadioRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_summary', models.TextField(verbose_name='Clinical Summary')),
                ('request_notes', models.TextField(verbose_name='X-Ray requested/USS')),
                ('request_time', models.TimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encounter.Encounter')),
            ],
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='patientradiorequest',
            name='request_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiology.RequestStatus'),
        ),
        migrations.AddField(
            model_name='patientradiorequest',
            name='requestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientradioreport',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiology.PatientRadioRequest'),
        ),
    ]
