# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientradioreport',
            name='report',
            field=models.TextField(blank=True, null=True, verbose_name='Report'),
        ),
    ]
